version: '3.8'

networks:
  retail-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: retail_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=retail
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retail-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retail_backend
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=retail
      - GOOGLE_CLOUD_PROJECT=boost-446418
      - GCS_BUCKET_NAME=boost-446418-dev-products
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/.config/gcloud/application_default_credentials.json:ro
    networks:
      - retail-network

  frontend:
    build:
      context: ./retail-frontend
      dockerfile: Dockerfile.dev
    container_name: retail_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./retail-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000
    command: npm start
    depends_on:
      - backend
    networks:
      - retail-network

  init_db:
    build:
      context: ./initializer
      dockerfile: Dockerfile
    container_name: retail_init_db
    depends_on:
      mysql:
        condition: service_healthy
    command: ["poetry", "run", "python", "initialize_database.py"]
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=retail
      - GOOGLE_CLOUD_PROJECT=boost-446418
      - GCS_BUCKET_NAME=boost-446418-dev-products
      - BACKEND_URL=http://backend:8000
      - GCS_IMAGE_KEY=brendanheadshot
      - IMAGE_PATH=sample.png
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/root/.config/gcloud/application_default_credentials.json:ro
    networks:
      - retail-network
